package com.briup.apps.ej.dao;

import com.briup.apps.ej.bean.Order;
import com.briup.apps.ej.bean.OrderExample;
import java.util.List;

import com.briup.apps.ej.bean.extend.orderExtend;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int deleteByPrimaryKey(Long id);//1.删除订单（查询删除）

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insert(Order record);//2.插入订单

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    //Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_order
     *
     * @mbg.generated Mon Jun 10 13:33:10 CST 2019
     */

    int updateByPrimaryKey(Order record);//3.更新订单

    orderExtend findAllOrderById(Long id);//4.查询订单

    List<Order> findAllOrder();//5.查询所有订单

   // List<Order> query(Order order);//6.模糊查询订单


}