package com.briup.apps.ej.service;

import com.briup.apps.ej.bean.CategoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CategoryService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int insert(com.briup.apps.ej.bean.Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int insertSelective(com.briup.apps.ej.bean.Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    List<com.briup.apps.ej.bean.Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    com.briup.apps.ej.bean.Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") com.briup.apps.ej.bean.Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int updateByExample(@Param("record") com.briup.apps.ej.bean.Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int updateByPrimaryKeySelective(com.briup.apps.ej.bean.Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ej_category
     *
     * @mbg.generated Mon Jun 10 11:21:59 CST 2019
     */
    int updateByPrimaryKey(com.briup.apps.ej.bean.Category record);
}
